version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: description
        must_exclude:
          regex: \[ ]
          message: All checkboxes must be checked
      - do: description
        must_exclude:
          regex: 'Please include some details of the security impact'
          message: You must fill out Security Impact
